### ISSUE TITLE
Refactor UI to handle international text

### ISSUE THREAD

**Issue by schue** [filterbubbler/filterbubbler-web-ext#51]
WebExtensions already provide a mature internationalization framework. Read more here:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization

**Comment by biancadanforth** [comment]
@schue Seems like there are a few parts here, but as I have yet to do this myself, perhaps you could confirm:
* Create a `_locales` subfolder in the `./extensions` directory.
* Create a `en` subfolder within `./extension/_locales`
* Create a `messages.json` file within `.extension/_locales/en`
* Using [this example](https://github.com/mdn/webextensions-examples/blob/master/notify-link-clicks-i18n/_locales/en/messages.json) as a point of departure along with the FilterBubbler UI, create the initial set of message strings needed for all the text in the UI, including variables that need to be passed in.
* Replace the strings in the UI with these new, localized message strings using the [`i18n`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n) extension API.
  * How does the extension detect the user's language? I don't see where this is done in the [example](https://github.com/mdn/webextensions-examples/tree/master/notify-link-clicks-i18n) from [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Internationalization).
* After a first `messages.json` is created, this can be used as a template for other languages to be added into the `_locales` directory.
